parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  comma-dangle:
    - error
    - always-multiline
  eol-last:
    - error
    - always
  "@typescript-eslint/indent":
    - error
    - 4
  "@typescript-eslint/no-unused-vars": warn
  no-compare-neg-zero: error
  no-const-assign: error
  no-sparse-arrays: error
  no-unsafe-finally: error
  no-unsafe-negation: error
  capitalized-comments:
    - error
    - never
  eqeqeq: error
  dot-notation: error
  no-eval: error
  no-extra-boolean-cast: error
  no-lonely-if: error
  no-unneeded-ternary: error
  no-warning-comments:
    - error
    - terms:
        - todo
      location: anywhere
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  yoda: warn
