version: "3.8"
name: file-share
services:
  backend:
    image: wuguishifu/file-share:backend
    container_name: backend 
    environment:
      - "PORT=8080"
      - "NODE_ENV=production"
    ports:
      - "3000:8080"
    restart: unless-stopped
    volumes:
      - C:/Users/brame/Developer/data/file-share:/data
