version: "3.8"
name: file-share
services:
  backend:
    image: wuguishifu/file-share:backend
    container_name: backend 
    environment:
      - "PORT=8080"
    network_mode: host
    restart: unless-stopped
    volumes:
      - C:/Users/brame/Developer/data/file-share:/data
