version: "3.8"
name: file-share
services:
  backend:
    image: wuguishifu/file-share:backend
    container_name: backend 
    environment:
      - "PORT=8080"
      - "NODE_ENV=production"
      - "FIREBASE_API_KEY="
      - "FIREBASE_AUTH_DOMAIN="
      - "FIREBASE_PROJECT_ID="
      - "FIREBASE_STORAGE_BUCKET="
      - "FIREBASE_MESSAGING_SENDER_ID="
      - "FIREBASE_APP_ID="
      - "FIREBASE_MEASUREMENT_ID="
      - "FIREBASE_PRIVATE_KEY_ID="
      - "FIREBASE_PRIVATE_KEY="
      - "FIREBASE_CLIENT_EMAIL="
    ports:
      - "3000:8080"
    restart: unless-stopped
    volumes:
      - C:/Users/brame/Developer/data/file-share:/data
